### ISSUE TITLE
Dúvida sobre a lib

### ISSUE THREAD

**Issue by Drieger** [tuliofaria/sigep#2]
Olá, gostaria de saber se a lib continua em desenvolvimento? Vi que o último commit é de 13 dias atrás, mas antes disso não havia nada desde 2018. Quais as perspectivas pra essa lib?

**Comment by RenatoSiqueira** [comment]
> Olá, gostaria de saber se a lib continua em desenvolvimento? Vi que o último commit é de 13 dias atrás, mas antes disso não havia nada desde 2018. Quais as perspectivas pra essa lib?

Olá Drieger!
O webservice dos correios praticamente nao sofreu atualizações, então a versão de 2018 ainda estava funcional.

Fizemos a atualização pra usar async/await, promisses e simplificar o código (que era um pouco mais verboso)

Como usamos ela em sistemas internos, tem poucas chances de ser descontinuada.
Abraço!

**Comment by Drieger** [comment]
Ok, muito obrigado.
